export const IMAGES = {
  alert: require('../assets/images/icons/alert-circle.png'),
  bank: require('../assets/images/icons/bank.png'),
  burger: require('../assets/images/icons/Burger.png'),
  check: require('../assets/images/icons/check.png'),
  chevron_left: require('../assets/images/icons/chevron-left.png'),
  cocktail: require('../assets/images/icons/Cocktail.png'),
  credit_card: require('../assets/images/icons/credit-card.png'),
  discount: require('../assets/images/icons/discount.png'),
  error: require('../assets/images/icons/error_outline_24px.png'),
  facebook: require('../assets/images/icons/Facebook_Icon.png'),
  frame: require('../assets/images/icons/Frame 2.png'),
  gift: require('../assets/images/icons/gift.png'),
  google: require('../assets/images/icons/Google_Icon.png'),
  heart: require('../assets/images/icons/heart.png'),
  home: require('../assets/images/icons/home.png'),
  list: require('../assets/images/icons/list_alt_24px.png'),
  support: require('../assets/images/icons/live support agent headset.png'),
  log_out: require('../assets/images/icons/log-out.png'),
  macaroons: require('../assets/images/icons/Macaroons.png'),
  map: require('../assets/images/icons/map-pin.png'),
  time: require('../assets/images/icons/mdi_access_time.png'),
  star: require('../assets/images/icons/Star.png'),
  steak: require('../assets/images/icons/Steak.png'),
  tag: require('../assets/images/icons/tag.png'),
  user: require('../assets/images/icons/user.png'),
  ticket: require('../assets/images/ticket.png'),
  x: require('../assets/images/icons/x.png'),
  down: require('../assets/images/icons/arrowDown.png'),
  search: require('../assets/images/icons/search.png'),
  dot: require('../assets/images/icons/dot16.png'),
};
